#include "images.h"

const ext_img_desc_t images[27] = {
    { "BG_MainScreen", &img_bg_main_screen },
    { "ico_temp", &img_ico_temp },
    { "ico_humidity", &img_ico_humidity },
    { "ico_main_home", &img_ico_main_home },
    { "wifi_off", &img_wifi_off },
    { "wifi_on", &img_wifi_on },
    { "ico_bluetoot", &img_ico_bluetoot },
    { "ico_no_battery", &img_ico_no_battery },
    { "ico_weater", &img_ico_weater },
    { "ico_settings", &img_ico_settings },
    { "ico_pressure", &img_ico_pressure },
    { "ico_heating_64x64", &img_ico_heating_64x64 },
    { "ico_heating_32x32", &img_ico_heating_32x32 },
    { "ico_energy_power_64x64", &img_ico_energy_power_64x64 },
    { "ico_humidity_64_64", &img_ico_humidity_64_64 },
    { "ico_high_temp", &img_ico_high_temp },
    { "ico_low_temperature", &img_ico_low_temperature },
    { "ico_low_humidity_32_32", &img_ico_low_humidity_32_32 },
    { "img_ball_temp_indicator", &img_img_ball_temp_indicator },
    { "img_ball_humidity_16_16", &img_img_ball_humidity_16_16 },
    { "img_battery_not_present", &img_img_battery_not_present },
    { "img_wifi_off", &img_img_wifi_off },
    { "img_Bluetooth_disabled", &img_img_bluetooth_disabled },
    { "img_sdcard", &img_img_sdcard },
    { "img_meteo_sun", &img_img_meteo_sun },
    { "img_meteo_sun_clougy", &img_img_meteo_sun_clougy },
    { "img_wifi_on", &img_img_wifi_on },
};
